function Hd = lpf400
%LPF400 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 13-Jul-2020 22:59:45

% IIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Nb   = 8;    % Numerator Order
Na   = 8;    % Denominator Order
F3dB = 400;  % 3-dB Frequency

h  = fdesign.lowpass('Nb,Na,F3dB', Nb, Na, F3dB, Fs);
Hd = design(h, 'butter');

% [EOF]
